name:    neon
default: all

properties:
  name:      neon
  build_dir: build

targets:

  all:
    depends: [clean, test, compile]

  clean:
    steps:
    - "rm -rf #{build_dir}"

  test:
    steps:
    - "go test"

  compile:
    steps:
    - "mkdir -p #{build_dir}"
    - "go build -o #{build_dir}/#{name}"

