name:    neon
default: compile

properties:
  name:      neon
  build_dir: build

targets:

  clean:
    steps:
    - "rm -rf #{build_dir}"

  test:
    steps:
    - "go test"

  compile:
    depends: [clean, test]
    steps:
    - "mkdir -p #{build_dir}"
    - "go build -o #{build_dir}/#{name}"

