name: neon
default: [clean, test, build]
doc: "Build file to build neon"

properties:
  name:      neon
  version:   0.1.0
  build_dir: build

targets:

  deps:
    doc: "Install libraries"
    steps:
    - "go get gopkg.in/yaml.v2"
    - "go get github.com/fatih/color"
    - "go get github.com/mitchellh/gox"
    - "go get github.com/mattn/anko"

  test:
    doc: "Run unit tests"
    steps:
    - "go test"

  build:
    doc: "Build neon binary"
    steps:
    - "mkdir -p #{build_dir}"
    - "go build -o #{build_dir}/#{name}"

  archive:
    depends: clean
    doc: "Generate distribution archive"
    steps:
    - "mkdir -p #{build_dir}/#{name}-#{version}/bin/"
    - "gox -output=#{build_dir}/#{name}-#{version}/bin/{{.Dir}}_{{.OS}}_{{.Arch}}"
    - "cp LICENSE.txt #{build_dir}/#{name}-#{version}/"
    - |
      cp README.md #{build_dir}/ &&
      cd #{build_dir} &&
      md2pdf README.md &&
      cp README.pdf #{name}-#{version}/
    - |
      cp CHANGELOG.yml #{build_dir}/ &&
      cd #{build_dir} &&
      changelog to markdown > CHANGELOG.md &&
      md2pdf CHANGELOG.md &&
      cp CHANGELOG.pdf #{name}-#{version}/
    - |
      cd #{build_dir} &&
      tar cvzf #{name}-bin-#{version}.tar.gz #{name}-#{version}

  release:
    depends: [clean, test, archive]
    doc: "Perform a release"
    steps:
    - "release"

  clean:
    doc: "Clean generated files"
    steps:
    - "rm -rf #{build_dir}"
