name: neon
default: [clean, test, bin]
doc: "Build file to build neon"

properties:
  name:         "neon"
  version:      "0.1.0"
  build_dir:    "build"
  arc_dir:      "#{build_dir}/#{name}-#{version}"
  dependencies:
  - "gopkg.in/yaml.v2"
  - "github.com/fatih/color"
  - "github.com/mitchellh/gox"
  - "github.com/mattn/anko"
  - "github.com/mattn/go-zglob"

targets:

  deps:
    doc: "Install libraries"
    steps:
    - for: dependency
      in:  dependencies
      do:
      - "go get #{dependency}"

  test:
    doc: "Run unit tests"
    steps:
    - "go test #{name}/..."

  bin:
    doc: "Build neon binary"
    steps:
    - "go install #{name}"

  archive:
    depends: clean
    doc: "Generate distribution archive"
    steps:
    - mkdir: "#{arc_dir}/bin/"
    - "gox -output=#{arc_dir}/bin/{{.Dir}}_{{.OS}}_{{.Arch}} #{name}"
    - "cp LICENSE.txt #{arc_dir}/"
    - "md2pdf -o #{arc_dir}/README.pdf README.md"
    - "changelog to markdown > #{build_dir}/CHANGELOG.md"
    - "md2pdf -o #{arc_dir}/CHANGELOG.pdf #{build_dir}/CHANGELOG.md"
    - "rm #{build_dir}/CHANGELOG.md"
    - cd: "#{build_dir}"
    - "tar cvzf #{name}-#{version}.tar.gz #{name}-#{version}"

  release:
    depends: [clean, test, archive]
    doc: "Perform a release"
    steps:
    - "release"

  clean:
    doc: "Clean generated files"
    steps:
    - delete: "#{build_dir}"
